# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_car.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 361, 206))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelMod = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelMod.setObjectName("labelMod")
        self.horizontalLayout_2.addWidget(self.labelMod)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEditModel = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditModel.setObjectName("lineEditModel")
        self.horizontalLayout_2.addWidget(self.lineEditModel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelCol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelCol.setObjectName("labelCol")
        self.horizontalLayout_7.addWidget(self.labelCol)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.lineEditColor = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditColor.setObjectName("lineEditColor")
        self.horizontalLayout_7.addWidget(self.lineEditColor)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelVin = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelVin.setObjectName("labelVin")
        self.horizontalLayout_6.addWidget(self.labelVin)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.lineEditVin = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditVin.setObjectName("lineEditVin")
        self.horizontalLayout_6.addWidget(self.lineEditVin)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelOwn = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelOwn.setObjectName("labelOwn")
        self.horizontalLayout_5.addWidget(self.labelOwn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lineEditOwn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditOwn.setObjectName("lineEditOwn")
        self.horizontalLayout_5.addWidget(self.lineEditOwn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.labeId = QtWidgets.QLabel(Dialog)
        self.labeId.setGeometry(QtCore.QRect(20, 30, 351, 16))
        self.labeId.setObjectName("labeId")
        self.pushButtonSaveCar = QtWidgets.QPushButton(Dialog)
        self.pushButtonSaveCar.setGeometry(QtCore.QRect(20, 260, 361, 20))
        self.pushButtonSaveCar.setObjectName("pushButtonSaveCar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelMod.setText(_translate("Dialog", "Модель"))
        self.labelCol.setText(_translate("Dialog", "Цвет"))
        self.labelVin.setText(_translate("Dialog", "vin-номер"))
        self.labelOwn.setText(_translate("Dialog", "Владелец"))
        self.labeId.setText(_translate("Dialog", "Id"))
        self.pushButtonSaveCar.setText(_translate("Dialog", "Сохранить"))
